# Generated by Django 4.2.5 on 2023-11-29 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getState', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state_data',
            name='id',
        ),
        migrations.AlterField(
            model_name='state_data',
            name='name',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
