# Generated by Django 4.2.5 on 2023-12-02 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getState', '0002_remove_state_data_id_alter_state_data_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='state_data',
            old_name='water_are',
            new_name='water_area',
        ),
    ]
